apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  labels:
      app: flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: ormoshe/class-8-argocd-gitops:latest
        command:
          - /bin/sh
          - -c
          - while true; do echo "$(date) My preferred sport is $(cat /etc/config/sport)";
            sleep 10; done;
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: my-config

