apiVersion: v1
kind: Service
metadata:
  name: class8-argocd-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 5000       # service port
      targetPort: 8080   # container port
  type: NodePort

